name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        path: h5p-course-presentation
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: |
        cd h5p-course-presentation
        npm install
        npm run build
    - run: |
        
        mkdir -p dist
        cd dist
        

        while read -r repo; do git clone ${repo}; done < ../h5p-course-presentation/build_info/repos
        if [ -d "h5p-editor-color-selector" ]; then cd h5p-editor-color-selector && git checkout b0ae8c941cedcec73df6b186663eae6df8679810; fi
        if [ -d "h5p-dialogcards" ]; then cd h5p-dialogcards && npm install && npm run build; fi
        if [ -d "h5p-drag-text" ]; then cd h5p-drag-text && npm install && npm run build; fi
        if [ -d "h5p-questionnaire" ]; then cd h5p-questionnaire && npm install && npm run build; fi
        if [ -d "h5p-drag-question" ]; then cd h5p-drag-question && npm install && npm run build; fi
        if [ -d "h5p-interactive-video" ]; then cd h5p-interactive-video && npm install && npm run build; fi
        if [ -d "h5p-open-ended-question" ]; then cd h5p-open-ended-question && npm install && npm run build; fi
        if [ -d "h5p-simple-multiple-choice" ]; then cd h5p-simple-multiple-choice && npm install && npm run build; fi
        

        rm -rf h5p-course-presentation h5p-editor-course-presentation h5p-chart h5p-shape h5p-editor-shape
        git clone https://github.com/NDLANO/h5p-chart.git
        git clone https://github.com/NDLANO/h5p-shape.git
        git clone https://github.com/NDLANO/h5p-editor-shape.git
        
        git clone https://github.com/NDLANO/h5p-editor-course-presentation.git
        
        cp -r ../h5p-course-presentation .
    - run: |
        cd dist
        ls
        npm install -g h5p
        h5p pack -r h5p-course-presentation interaktiv_tavle.h5p
        h5p validate interaktiv_tavle.h5p
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: interaktiv_tavle.h5p
        path: dist/interaktiv_tavle.h5p
